### ISSUE TITLE
Short Term Limit for short program

### ISSUE THREAD

**Issue by cchampet** [mikrosimage/loudness_validator#23]
According the current specification, R-128 expects a short term limit of -20 LUFS without tolerence (for short programs).
https://github.com/mikrosimage/loudness_validator/blob/develop/src/loudnessAnalyser/LoudnessAnalyser.hpp#L140

**Comment by cchampet** [comment]
Warning: this is a recommendation of CST-RT-017!! Not something of EBU-128!
Checkout with this specification: https://github.com/mikrosimage/loudness_validator/blob/develop/src/loudnessAnalyser/LoudnessAnalyser.hpp#L100

**Comment by cchampet** [comment]
The implementation of specifications seems to be correct.
However, with CST-RT-017 selected in loudness-validator, a short term of -19,4LUFS after analyse, is not written in red (it is green!).

**Comment by MarcAntoine-Arnaud** [comment]
It can be correct to have a Short Term between -23LUFS +-7LU for long program (>2'00) with the RT-017. It's designed to keep dynamic on long programs.
I think everything is okay.

**Comment by cchampet** [comment]
But we are talking about short program in this issue.
