### ISSUE TITLE
LoudnessAnalyser::processSamples: why the audio buffer contains float

### ISSUE THREAD

**Issue by cchampet** [mikrosimage/loudness_validator#27]
https://github.com/mikrosimage/loudness_validator/blob/30829c86cb859ad52d516980a217f10e97659414/src/loudnessAnalyser/LoudnessAnalyser.hpp#L218

Is it because libsndfile returns an array of float, or because of the loudness algorithm?

**Comment by MarcAntoine-Arnaud** [comment]
It can be explain with 2 reasons:
- audio don't take more memory space if we can consider we process 90% of 24bits audio, which need to be stored into a 32bits for process it.
- the algorithme requires filtering and sum's, which requires to switch into float to be able to support out of ranges values.
For that the only input available for this library is a float buffer. If you need to connect to another library, you may be able to convert to a float buffer.
