### ISSUE TITLE
Setup CI (use Travis)

### ISSUE THREAD

**Issue by cchampet** [mikrosimage/loudness_validator#32]

**Comment by cchampet** [comment]
The current problem is: 
SCons 2.3 or greater required, but Travis has SCons 2.1.0.
I've just sent a mail to the Travis team. Waiting for their feedback.

**Comment by MarcAntoine-Arnaud** [comment]
It isn't possible to install via pip the latest version of scons ?

**Comment by cchampet** [comment]
Yes it must be something with pip. But PLoud is a c++ project (for Travis jobs, to have compilers...), and because of that, we have not all python tools shown [here](http://docs.travis-ci.com/user/languages/python/).

**Comment by cchampet** [comment]
Fixed with this commit  b9ec5d7

**Comment by cchampet** [comment]
README: the badge is missing.

**Comment by cchampet** [comment]
See PR #40
